- name: variables to print
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
    - name: print the course information
      ansible.builtin.debug:
        msg: "Hi, I'm learning {{COURSE}}, duration is {{DURATION}}, Trainer is {{TRAINER}}"  