- name: variables to prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
    private: false

  - name: TRAINER
    prompt: please enter trainer name
    private: false  

  - name: DURATION
    prompt: please enter duration name
    private: false

  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "Hi, I'm learning {{COURSE}}, duration is {{DURATION}}, Trainer is {{TRAINER}}"  