- name: variables to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "120HRS"
    TRAINER: "Sivakumar"
  vars_files:
  - vars.yaml  
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
    private: false
  tasks:
  - name: please enter the course info
    vars:
     #COURSE: "ansible"
      DURATION: "120HRS"
      TRAINER: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hi, i'm learning {{COURSE}}"   

