---
- name: install packages using loop
  hosts: web
  become: yes
  tasks:
    - name: install given packages using loop
      ansible.builtin.package:
       name: "{{ item }}"
       state: present

      loop:
      - httpd
      - postfix
      - mysql  